# Generated by Django 5.0 on 2026-01-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='user_agent',
            field=models.CharField(blank=True, help_text='Brauzer user agent string', max_length=500, null=True, verbose_name='User Agent'),
        ),
    ]
