# Generated by Django 5.0 on 2026-02-08 18:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_add_null_to_user_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assigned_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Qurilma tayinlangan vaqt', verbose_name='Tayinlangan sana'),
        ),
    ]
